golang-base:
  env: local
  http-port: "13831"
golang-consul:
  host: 127.0.0.1
  port: "8500"
  token: XXXXXXXXXXXXXXXXXX
golang-golang-server:
  golang-audiocat: "13831"
  golang-dinghomework: "13831"
  http-port: "13831"
  rpc-port: "13832"
golang-mysql:
  char: utf8mb4
  db: hx
  host: 127.0.0.1
  password: Sy9rYTVPTnQrRSt1UlI4
  port: "3307"
  user: fordevtest
golang-mysql-bat:
  char: utf8mb4
  db: hx
  host: 127.0.0.1
  password: qBs!c27Mqw
  port: "3307"
  user: root
golang-oss:
  access-key-id: XXXXXXXXXXXXXXXXXX
  access-key-secret: XXXXXXXXXXXXXXXXXX
  bucket-name: XXXXXXXXXXXXXXXXXX
  endpoint: XXXXXXXXXXXXXXXXXX
  role-arn: XXXXXXXXXXXXXXXXXX
golang-redis-data:
  host: 127.0.0.1
  match-host: 127.0.0.1
  password: ""
  port: "6379"
golang-redis-key:
  host: 127.0.0.1
  match-host: 127.0.0.1
  password: ""
  port: "6379"
python-amqp:
  access-key-id: XXXXXXXXXXXXXXXXXX
  access-key-secret: XXXXXXXXXXXXXXXXXX
  address: XXXXXXXXXXXXXXXXXX
  instance-id: XXXXXXXXXXXXXXXXXX
